version: "3"

services:
  frontend:
    build:
      context: "./Frontend/Docker"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app/frontend
    command: bash entrypoint

  backend:
    build:
      context: "./Backend/Docker"
      dockerfile: Dockerfile
    # ports could change later with addition to API code(?)
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app/backend
